### ISSUE TITLE
it seems like render.js does not pass correct value to map.render()

### ISSUE THREAD

**Issue by wsw0108** [mapbox/tilelive-mapnik#99]
https://github.com/mapbox/tilelive-mapnik/blob/master/lib/render.js#L194-L202
but the 'options' passed to map.render(image/grid/vectortile, options, callback) may should contains 'offset_x', 'offset_y', according to below:
https://github.com/mapnik/node-mapnik/blob/master/src/mapnik_map.cpp#L1616-L1634

Do i mismatch those params?

**Comment by springmeyer** [comment]
`options.x` and `options.y` are passed to one of https://github.com/mapbox/tilelive-mapnik/blob/master/lib/render.js#L208-L212. They are ignored by node-mapnik, harmlessly. So, you are correct to point out that this is odd looking. But those options are intentional - they are not meant to be `offset_x`, etc. So clearer code might create two sets of options, one to pass to node-mapnik and one to pass to the tile cutting functions.

**Comment by wsw0108** [comment]
I understand.
Thanks for you answer.
